#!/bin/bash

#    PPA Uploader: GUI tool for uploading packages to a PPA on launchpad.net.
#    Copyright (C) 2017  Pavel Řehák
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

# version 0.2.0
# depend on zenity

config_file=$HOME/.config/ppa-uploader/config


##############################################################################
# Gettext
##############################################################################

. gettext.sh

TEXTDOMAIN=ppa-uploader
export TEXTDOMAIN

TEXTDOMAINDIR=/usr/share/locale
export TEXTDOMAINDIR

title=$(gettext 'PPA Uploader')


##############################################################################
#	FUNCTIONS
##############################################################################

main_window()
{
settings_str=$(gettext 'Settings...')
upload_str=$(gettext 'Upload...')
exit_str=$(gettext 'Exit')

action=$(zenity --list \
				--height=205 \
				--title="$title" \
				--text "$(gettext 'Choose action')" \
				--column "$(gettext 'Action')" \
				$settings_str $upload_str $exit_str)
}

settings_window()
{
if user_ppa=$(zenity --entry \
		--title="$title" \
		--text="$(gettext 'Set user name and name of your PPA in format: 
 user/ppa')" \
		--entry-text="$(cat $config_file)")
then
	echo $user_ppa > $config_file || create_config
fi
}

create_config()
{
mkdir  $HOME/.config/ppa-uploader
echo $user_ppa > $config_file
}

upload_file()
{
user_ppa="$(cat $config_file)"
if [ "$user_ppa" = "" ]
then
	error_window
else
	if path_file=$(zenity --file-selection \
					--filename="$HOME/" \
					--title="$title" \
					--file-filter="source.changes | *source.changes")
	then
		# Print the part of string after last "/"
		file_name=$(echo "${path_file##*/}")
		if zenity --question \
					--title="$title" \
					--text="$(eval_gettext "Do you want to upload \$file_name to \$user_ppa?")" \
					--default-cancel
		then
			command_upload="dput ppa:$user_ppa $path_file"
			log="$(eval $command_upload)"
			zenity --info \
					--text="$log" \
					--title="$title" \
		else
			:
		fi
	else
		:
	fi
fi
}

error_window()
{
zenity --warning \
		--text="$(gettext 'Set user name and name of your PPA in Settings first.')" \
		--title="$title"
}

##############################################################################
#	PROGRAM
##############################################################################

run=1
while [ "$run" = 1 ]
do

main_window

if [ $action = $upload_str ]
then
	upload_file
elif [ $action = $settings_str ]
then
	settings_window
else
	run=0
fi

done
