.\" (C) Copyright 2018 Pavel Rehak <pavel-rehak@email.cz>,
.\"
.TH DEB-CUP 1 "April 17 2018"
.\" Please adjust this date whenever revising the manpage.
.\"
.SH NAME
deb-cup \- GUI tool for creating deb packages and uploading to a PPA
.SH SYNOPSIS
.B deb-cup
.RI [ option ]
.SH DESCRIPTION
.B deb-cup
is a GUI tool for creating deb packages and uploading to a PPA on
launchpad.net.
.PP
.SH OPTIONS
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-v, \-\-version
Show the deb-cup version.
